
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class placement_officer_list_admin extends javax.swing.JFrame {

    
        Connection con1;
        PreparedStatement insert;
        String result;
        
        
        public void tableupdate(){  
            
  
  
        // order
        
                try {
       Class.forName("com.mysql.cj.jdbc.Driver");
       Connection kk;
       kk = DriverManager.getConnection	("jdbc:mysql://localhost:3307/campus_recruitment_system","root","");
        Statement stmt = kk.createStatement();
        String sql="set @autoid :=0";
 	String sql1="update tpo_registration set `S.No` = @autoid := (@autoid+1);";
 	String sql2="alter table tpo_registration Auto_Increment = 1 ";
        
        String q1="set @autoid :=0";
 	String q2="update tpo_login set `S.No` = @autoid := (@autoid+1);";
 	String q3="alter table tpo_login Auto_Increment = 1 ";
		ResultSet k1;
		ResultSet k2;
		ResultSet k3;
		 stmt.executeUpdate(sql);
		 stmt.executeUpdate(sql1);
                 stmt.executeUpdate(sql2);
                  stmt.executeUpdate(q1);
		 stmt.executeUpdate(q2);
                 stmt.executeUpdate(q3);
}
catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } 
            
            
            //table view
            
             
    int  c;
     
     try {
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection con;
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3307/campus_recruitment_system","root","");
                        Statement stmt = con.createStatement();
                        String sql="SELECT `S.No`,`F_Name`, `L_Name`, `DOB`, `Gender`, `Email_Id`, `Phone_Number`, `Staff_Admin` FROM `tpo_registration`";
                        ResultSet rs = stmt.executeQuery(sql);
            
            ResultSetMetaData RSMD = rs.getMetaData();
            c = RSMD.getColumnCount();
            
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);
            
            while (rs.next()) {
                Vector v2 = new Vector();
           
                for(int a=1;a<=c;a++) {
                    v2.add(rs.getString("S.No"));
                    v2.add(rs.getString("F_Name"));
                    v2.add(rs.getString("L_Name"));
                    v2.add(rs.getString("DOB"));
                    v2.add(rs.getString("Gender"));
                    v2.add(rs.getString("Email_Id"));
                    v2.add(rs.getString("Phone_Number"));
                    v2.add(rs.getString("Staff_Admin"));
                }
                DFT.addRow(v2);
            }   
            
     }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } 
     
     
     
}
    
    
    public placement_officer_list_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jPanel2.setBackground(new java.awt.Color(255, 51, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Placement Officer List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "F_Name", "L_Name", "DOB", "Gender", "Email_Id", "Phone_Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("F_Name");

        txtfname.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("L_Name");

        txtlname.setText(" ");

        txtdob.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DOB");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        txtgender.setText(" ");

        txtmail.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone_Number");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtfname)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtlname)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdob)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgender)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmail)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtnumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // back to admin homme
            admin_home sl=new admin_home();
            sl.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
            
        //selected jtable
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
         int selectedIndex = jTable1.getSelectedRow();
        
                    txtfname.setText(df.getValueAt(selectedIndex, 1).toString());
                    txtlname.setText(df.getValueAt(selectedIndex, 2).toString());
                    txtdob.setText(df.getValueAt(selectedIndex, 3).toString());
                    txtgender.setText(df.getValueAt(selectedIndex, 4).toString());
                    
                    txtmail.setText(df.getValueAt(selectedIndex, 5).toString());
                    txtnumber.setText(df.getValueAt(selectedIndex, 6).toString());
                    //txtdob.setText(df.getValueAt(selectedIndex, 3).toString());
                    
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
         int selectedIndex = jTable1.getSelectedRow();
        
         try{
            // int sno = Integer.parseInt(tb.getValueAt(selectedIndex,0).toString());
             String name=tb.getValueAt(selectedIndex,1).toString();
             int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to delete","Warning",JOptionPane.YES_NO_OPTION);
             if(dialogResult == JOptionPane.YES_OPTION)
                    {
                        Connection con;
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3307/campus_recruitment_system","root","");
                        PreparedStatement insert;
                        insert=con.prepareStatement("delete from tpo_registration where F_Name= ?");
                        insert.setString(1,name);
                        insert.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted");
                        tableupdate();  
                    }
         }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"1" +e);
            
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       //update
       
         String c=txtgender.getText();
                 String n=txtnumber.getText();
                 String fname=txtfname.getText();
                 String lname=txtlname.getText();
              String mail=txtmail.getText();
              String mobile=txtnumber.getText();
              String dob=txtdob.getText();
              int sc_num=0;
              // special character and number count
              
              
        if(fname.isEmpty() ||lname.isEmpty() ||mail.isEmpty() ||mobile.isEmpty() ||dob.isEmpty() ||c.isEmpty()){
            JOptionPane.showMessageDialog(this, "All feilds are Mandatory!!!. ");
        }
        else
        {
         DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
         int selectedIndex = jTable1.getSelectedRow();
         
         
                 
                 int nl=n.length();
                 int count=0;
        char a;
        a=c.charAt(0);
         String kk="";
        if(c.length()>1||c.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Enter M or F or O.");
        }
        else if(nl<10 || nl>10)
        {
            JOptionPane.showMessageDialog(this, "Enter Mobile Number in Correct Format. ");
        }        
        else if(c.length()==1) {
   
            if(a=='M' || a=='m'){
                kk="M";
                
                
            }else if(a=='f' || a=='F'){
                kk="f";
                
            }else if(a=='O' || a=='o'){
                kk="o";
                
            }
            if(kk.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Enter your gender in correct format \n                 M for Male\n                 F for Female\n                 O for Others. ");
            }
            else{
                if(fname.length()!=0)
                {
                    Pattern my_pattern = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
                    Matcher my_match = my_pattern.matcher(fname);
                    boolean check = my_match.find();
                    if (check){
                    JOptionPane.showMessageDialog(this, "Special characters and numbers are not allowed in name feilds. ");
                    sc_num+=1;
                    }
                    
                    if(sc_num==0)
                    {
                           // check for number
                     for (int i = 0; i < fname.length(); i++) { 
                            if (fname.charAt(i) >= '0'&& fname.charAt(i) <= '9') { 
                            JOptionPane.showMessageDialog(this, "Special characters and numbers are not allowed in name feilds . ");
                            sc_num+=1;
                            break;
                            }       
                        }
                        
                    }
                 
                     if(sc_num==0)
                     {
                        Pattern my_pattern1 = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
                        Matcher my_match1= my_pattern.matcher(lname);
                        boolean check1 = my_match.find();
                        if (check1){
                           JOptionPane.showMessageDialog(this, "Special characters and numbers are not allowed in name feilds. ");
                           sc_num+=1;
                        }
                     }
                     if(sc_num==0)
                      {
                        // check for numbers
                        for (int i = 0; i < lname.length(); i++) { 
                            if (lname.charAt(i) >= '0'&& lname.charAt(i) <= '9') { 
                                JOptionPane.showMessageDialog(this, "Special characters and numbers are not allowed in name feilds . ");
                                sc_num+=1;
                                break;
                        
                                }         
                            }
                      }



                      if(sc_num==0)
                      {
                          try {

                                          String name=tb.getValueAt(selectedIndex,1).toString();
                                        // int id = Integer.parseInt(tb.getValueAt(selectedIndex, 0).toString());  
                                         // String fname=txtfname.getText();
                                         //String gender=txtgender.getText();
                                          Connection con;

                                          con = DriverManager.getConnection("jdbc:mysql://localhost:3307/campus_recruitment_system","root","");
                                          insert=con.prepareStatement("update tpo_registration set F_Name= ?,L_Name= ?,DOB=?,Gender=?,Email_Id= ?,Phone_Number= ? where F_Name= ?");


                                        insert.setString(1,fname);
                                        insert.setString(2,lname);
                                        insert.setString(3,dob);
                                        insert.setString(4,kk);

                                        insert.setString(5,mail);
                                        insert.setString(6,mobile);
                                        insert.setString(7,name);

                                        insert.executeUpdate();

                                        JOptionPane.showMessageDialog(this, "Record Updated");


                                        txtfname.setText("");
                                        txtlname.setText("");
                                        txtmail.setText("");
                                        txtnumber.setText("");
                                        txtdob.setText("");
                                        txtgender.setText("");

                                        tableupdate();
                                          }             
                                            catch (SQLException e) {
                                          JOptionPane.showMessageDialog(this, "Input data in correct format. " + e);
                                         // Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
                                      }
                          
                            
                                }                       
                            }
                        }
                    }
                }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placement_officer_list_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placement_officer_list_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placement_officer_list_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placement_officer_list_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placement_officer_list_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnumber;
    // End of variables declaration//GEN-END:variables
}
